-- Criação da tabela EMPREGADO
CREATE TABLE EMPREGADO (
    Nome VARCHAR2(50),
    RG VARCHAR2(10) PRIMARY KEY,
    CIC VARCHAR2(11),
    Depto INT,
    RG_Supervisor VARCHAR2(10),
    Salario DECIMAL(8, 2),
    CONSTRAINT fk_empregado_supervisor FOREIGN KEY (RG_Supervisor) REFERENCES EMPREGADO(RG)
);

-- Inserção de dados na tabela EMPREGADO
INSERT INTO EMPREGADO VALUES ('João Luiz', '10101010', '11111111', 1, NULL, 3000.00);
INSERT INTO EMPREGADO VALUES ('Fernando', '20202020', '22222222', 2, '10101010', 2500.00);
INSERT INTO EMPREGADO VALUES ('Ricardo', '30303030', '33333333', 2, '10101010', 2300.00);
INSERT INTO EMPREGADO VALUES ('Jorge', '40404040', '44444444', 2, '20202020', 4200.00);
INSERT INTO EMPREGADO VALUES ('Renato', '50505050', '55555555', 3, '20202020', 1300.00);

-- Criação da tabela DEPARTAMENTO
CREATE TABLE DEPARTAMENTO (
    Nome VARCHAR2(50),
    Numero INT PRIMARY KEY,
    RG_Gerente VARCHAR2(10),
    CONSTRAINT fk_departamento_gerente FOREIGN KEY (RG_Gerente) REFERENCES EMPREGADO(RG)
);

-- Inserção de dados na tabela DEPARTAMENTO
INSERT INTO DEPARTAMENTO VALUES ('Contabilidade', 1, '10101010');
INSERT INTO DEPARTAMENTO VALUES ('Engenharia Civil', 2, '30303030');
INSERT INTO DEPARTAMENTO VALUES ('Engenharia Mecânica', 3, '20202020');

-- Criação da tabela PROJETO
CREATE TABLE PROJETO (
    Nome VARCHAR2(50),
    Numero INT PRIMARY KEY,
    Localizacao VARCHAR2(50)
);

-- Inserção de dados na tabela PROJETO
INSERT INTO PROJETO VALUES ('Financeiro', 5, 'São Paulo');
INSERT INTO PROJETO VALUES ('Motor', 10, 'Rio Claro');
INSERT INTO PROJETO VALUES ('Prédio Central', 20, 'Campinas');

-- Criação da tabela DEPENDENTES
CREATE TABLE DEPENDENTES (
    RG_Responsavel VARCHAR2(10),
    Nome_Dependentes VARCHAR2(50),
    Nascimento DATE,
    Relacao VARCHAR2(20),
    Sexo VARCHAR2(10),
    CONSTRAINT fk_dependentes_empregado FOREIGN KEY (RG_Responsavel) REFERENCES EMPREGADO(RG)
);

-- Inserção de dados na tabela DEPENDENTES
INSERT INTO DEPENDENTES VALUES ('10101010', 'Jorge', TO_DATE('27/12/1986', 'DD/MM/YYYY'), 'Filho', 'Masculino');
INSERT INTO DEPENDENTES VALUES ('10101010', 'Luiz', TO_DATE('18/11/1979', 'DD/MM/YYYY'), 'Filho', 'Masculino');
INSERT INTO DEPENDENTES VALUES ('20202020', 'Fernanda', TO_DATE('14/02/1969', 'DD/MM/YYYY'), 'Cônjuge', 'Feminino');
INSERT INTO DEPENDENTES VALUES ('20202020', 'Ângelo', TO_DATE('10/02/1995', 'DD/MM/YYYY'), 'Filho', 'Masculino');
INSERT INTO DEPENDENTES VALUES ('30303030', 'Adreia', TO_DATE('01/05/1990', 'DD/MM/YYYY'), 'Filho', 'Feminino');

-- Criação da tabela DEPARTAMENTO_PROJETO
CREATE TABLE DEPARTAMENTO_PROJETO (
    Numero_Depto INT,
    Numero_Projeto INT,
    CONSTRAINT fk_dept_proj_depto FOREIGN KEY (Numero_Depto) REFERENCES DEPARTAMENTO(Numero),
    CONSTRAINT fk_dept_proj_proj FOREIGN KEY (Numero_Projeto) REFERENCES PROJETO(Numero)
);

-- Inserção de dados na tabela DEPARTAMENTO_PROJETO
INSERT INTO DEPARTAMENTO_PROJETO VALUES (2, 5);
INSERT INTO DEPARTAMENTO_PROJETO VALUES (3, 10);
INSERT INTO DEPARTAMENTO_PROJETO VALUES (2, 20);

-- Criação da tabela EMPREGADO_PROJETO
CREATE TABLE EMPREGADO_PROJETO (
    RG_Empregado VARCHAR2(10),
    Numero_Projeto INT,
    Horas INT,
    CONSTRAINT fk_empregado_projeto_emp FOREIGN KEY (RG_Empregado) REFERENCES EMPREGADO(RG),
    CONSTRAINT fk_empregado_projeto_proj FOREIGN KEY (Numero_Projeto) REFERENCES PROJETO(Numero)
);

-- Inserção de dados na tabela EMPREGADO_PROJETO
INSERT INTO EMPREGADO_PROJETO VALUES ('20202020', 5, 10);
INSERT INTO EMPREGADO_PROJETO VALUES ('20202020', 10, 25);
INSERT INTO EMPREGADO_PROJETO VALUES ('30303030', 5, 35);
INSERT INTO EMPREGADO_PROJETO VALUES ('40404040', 20, 50);
INSERT INTO EMPREGADO_PROJETO VALUES ('50505050', 20, 35);

